/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobaladiinvernonpizzurro;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author kathe0710
 */
public class Vista extends javax.swing.JFrame {
    
    //Contador de ciudades existentes en la partida
        int cityCounter=0;
        
    
    public Vista() {
                
        initComponents();
        
        //Inicializacion de los paneles y botones 
        jPanelNewGame.setVisible(false);
        jPanelInstruction.setVisible(false);
        NewCityjPanel.setVisible(false);
        jPanelInstruction.setSize(720, 720);
        
        //Texto a mostrar en dos de los labels
        CityNamejLabel1.setText("Nombre de la ciudad nº");
        CityDistancejLabel.setText("Distancia respecto a ");
        
        /*NewGamejButton.setBackground(Color.cyan);
        NewGamejButton.setForeground(Color.BLACK);*/
                          
        if (CustomValuesButton.isSelected()) {
        
            βValueInput.setEnabled(true);
            αValueInput.setEnabled(true);
            ρValueInput.setEnabled(true);
        } 
        else {
            βValueInput.setEnabled(false);
            αValueInput.setEnabled(false);
            ρValueInput.setEnabled(false);
        }
        
        UIManager.put("TextField.disabledBackground", Color.RED);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInstruction = new javax.swing.JPanel();
        jPanelNewGame = new javax.swing.JPanel();
        AntsNumjLabel = new javax.swing.JLabel();
        AddCityjButton = new javax.swing.JButton();
        DeleteCityjButton = new javax.swing.JButton();
        AntsNumInput = new javax.swing.JTextField();
        AntsNumValidationButton = new javax.swing.JButton();
        NewCityjPanel = new javax.swing.JPanel();
        CityNamejLabel1 = new javax.swing.JLabel();
        CityNameInput = new javax.swing.JTextField();
        CityNameValidationButton = new javax.swing.JButton();
        CityDistancejLabel = new javax.swing.JLabel();
        CityDistanceInput = new javax.swing.JTextField();
        CityDistanceValidationButton = new javax.swing.JButton();
        IterationsValidationButton = new javax.swing.JButton();
        IterationsInput = new javax.swing.JTextField();
        IterationsjLabel = new javax.swing.JLabel();
        ConfirmNewCityjButton = new javax.swing.JButton();
        StartGamejButton = new javax.swing.JButton();
        VariablesValuesjLabel1 = new javax.swing.JLabel();
        DefaultValuesButton = new javax.swing.JRadioButton();
        CustomValuesButton = new javax.swing.JRadioButton();
        ρValueInput = new javax.swing.JTextField();
        ρVariableValuejLabel = new javax.swing.JLabel();
        αValueInput = new javax.swing.JTextField();
        αVariableValuejLabel = new javax.swing.JLabel();
        βValueInput = new javax.swing.JTextField();
        βVariableValuejLabel = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        InstructionsjButton = new javax.swing.JButton();
        SavejButton = new javax.swing.JButton();
        LoadGamejButton = new javax.swing.JButton();
        ExitjButton = new javax.swing.JButton();
        NewGamejButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanelInstruction.setBackground(new java.awt.Color(213, 204, 206));
        jPanelInstruction.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instrucciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanelInstruction.setPreferredSize(new java.awt.Dimension(600, 500));

        javax.swing.GroupLayout jPanelInstructionLayout = new javax.swing.GroupLayout(jPanelInstruction);
        jPanelInstruction.setLayout(jPanelInstructionLayout);
        jPanelInstructionLayout.setHorizontalGroup(
            jPanelInstructionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        jPanelInstructionLayout.setVerticalGroup(
            jPanelInstructionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelNewGame.setBackground(new java.awt.Color(213, 204, 206));
        jPanelNewGame.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Partida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanelNewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelNewGame.setMaximumSize(new java.awt.Dimension(720, 720));
        jPanelNewGame.setPreferredSize(new java.awt.Dimension(600, 500));

        AntsNumjLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AntsNumjLabel.setText("Cantidad de hormigas");

        AddCityjButton.setBackground(new java.awt.Color(164, 225, 3));
        AddCityjButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddCityjButton.setText("Agregar ciudad");
        AddCityjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 168, 2), 2, true));
        AddCityjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCityjButtonActionPerformed(evt);
            }
        });

        DeleteCityjButton.setBackground(new java.awt.Color(249, 173, 107));
        DeleteCityjButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DeleteCityjButton.setText("Eliminar ciudad");
        DeleteCityjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 139, 45), 2, true));

        AntsNumInput.setBackground(new java.awt.Color(192, 178, 181));
        AntsNumInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AntsNumInput.setBorder(null);
        AntsNumInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntsNumInputActionPerformed(evt);
            }
        });

        AntsNumValidationButton.setBackground(new java.awt.Color(164, 225, 3));
        AntsNumValidationButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AntsNumValidationButton.setText("Aceptar");
        AntsNumValidationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 168, 2), 2, true));
        AntsNumValidationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntsNumValidationButtonActionPerformed(evt);
            }
        });

        NewCityjPanel.setBackground(new java.awt.Color(192, 178, 181));
        NewCityjPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Partida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        CityNamejLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        CityNameInput.setBackground(new java.awt.Color(215, 214, 213));
        CityNameInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CityNameInput.setBorder(null);
        CityNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityNameInputActionPerformed(evt);
            }
        });

        CityNameValidationButton.setBackground(new java.awt.Color(164, 225, 3));
        CityNameValidationButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CityNameValidationButton.setText("Aceptar");
        CityNameValidationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 168, 2), 2, true));
        CityNameValidationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityNameValidationButtonActionPerformed(evt);
            }
        });

        CityDistancejLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        CityDistanceInput.setBackground(new java.awt.Color(215, 214, 213));
        CityDistanceInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CityDistanceInput.setBorder(null);
        CityDistanceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityDistanceInputActionPerformed(evt);
            }
        });

        CityDistanceValidationButton.setBackground(new java.awt.Color(164, 225, 3));
        CityDistanceValidationButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CityDistanceValidationButton.setText("Aceptar");
        CityDistanceValidationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 168, 2), 2, true));
        CityDistanceValidationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityDistanceValidationButtonActionPerformed(evt);
            }
        });

        IterationsValidationButton.setBackground(new java.awt.Color(164, 225, 3));
        IterationsValidationButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        IterationsValidationButton.setText("Aceptar");
        IterationsValidationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 168, 2), 2, true));
        IterationsValidationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IterationsValidationButtonActionPerformed(evt);
            }
        });

        IterationsInput.setBackground(new java.awt.Color(215, 214, 213));
        IterationsInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        IterationsInput.setBorder(null);

        IterationsjLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        IterationsjLabel.setText("Número de iteraciones ");

        ConfirmNewCityjButton.setBackground(new java.awt.Color(164, 225, 3));
        ConfirmNewCityjButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ConfirmNewCityjButton.setText("Guardar ciudad");
        ConfirmNewCityjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 168, 2), 2, true));
        ConfirmNewCityjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmNewCityjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewCityjPanelLayout = new javax.swing.GroupLayout(NewCityjPanel);
        NewCityjPanel.setLayout(NewCityjPanelLayout);
        NewCityjPanelLayout.setHorizontalGroup(
            NewCityjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCityjPanelLayout.createSequentialGroup()
                .addGroup(NewCityjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewCityjPanelLayout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addGroup(NewCityjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityNamejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IterationsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CityDistancejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(NewCityjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NewCityjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CityDistanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(IterationsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CityNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(NewCityjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityNameValidationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IterationsValidationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CityDistanceValidationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewCityjPanelLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(ConfirmNewCityjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        NewCityjPanelLayout.setVerticalGroup(
            NewCityjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCityjPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NewCityjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CityNamejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NewCityjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CityNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CityNameValidationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(NewCityjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CityDistanceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityDistanceValidationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityDistancejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(NewCityjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IterationsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IterationsValidationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IterationsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ConfirmNewCityjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        StartGamejButton.setBackground(new java.awt.Color(164, 225, 3));
        StartGamejButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        StartGamejButton.setText("Comenzar");
        StartGamejButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 168, 2), 2, true));
        StartGamejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGamejButtonActionPerformed(evt);
            }
        });

        VariablesValuesjLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        VariablesValuesjLabel1.setText("Valores de β, α y ρ");

        DefaultValuesButton.setBackground(new java.awt.Color(213, 204, 206));
        DefaultValuesButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DefaultValuesButton.setText("Por defecto");
        DefaultValuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultValuesButtonActionPerformed(evt);
            }
        });

        CustomValuesButton.setBackground(new java.awt.Color(213, 204, 206));
        CustomValuesButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CustomValuesButton.setText("Personalizados");
        CustomValuesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomValuesButtonActionPerformed(evt);
            }
        });

        ρValueInput.setBackground(new java.awt.Color(192, 178, 181));
        ρValueInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ρValueInput.setBorder(null);

        ρVariableValuejLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ρVariableValuejLabel.setText("ρ");

        αValueInput.setBackground(new java.awt.Color(192, 178, 181));
        αValueInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        αValueInput.setBorder(null);

        αVariableValuejLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        αVariableValuejLabel.setText("α");

        βValueInput.setBackground(new java.awt.Color(192, 178, 181));
        βValueInput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        βValueInput.setBorder(null);

        βVariableValuejLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        βVariableValuejLabel.setText("β");

        javax.swing.GroupLayout jPanelNewGameLayout = new javax.swing.GroupLayout(jPanelNewGame);
        jPanelNewGame.setLayout(jPanelNewGameLayout);
        jPanelNewGameLayout.setHorizontalGroup(
            jPanelNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewGameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewCityjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNewGameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNewGameLayout.createSequentialGroup()
                                .addComponent(AddCityjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteCityjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNewGameLayout.createSequentialGroup()
                                .addComponent(βVariableValuejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(βValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(αVariableValuejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(αValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ρVariableValuejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ρValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNewGameLayout.createSequentialGroup()
                                .addGroup(jPanelNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNewGameLayout.createSequentialGroup()
                                        .addComponent(AntsNumjLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AntsNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelNewGameLayout.createSequentialGroup()
                                        .addComponent(VariablesValuesjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(DefaultValuesButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CustomValuesButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AntsNumValidationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(StartGamejButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelNewGameLayout.setVerticalGroup(
            jPanelNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNewGameLayout.createSequentialGroup()
                .addGroup(jPanelNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AntsNumjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AntsNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AntsNumValidationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomValuesButton)
                    .addComponent(VariablesValuesjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DefaultValuesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ρValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(αValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(βValueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(βVariableValuejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(αVariableValuejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ρVariableValuejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelNewGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCityjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteCityjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NewCityjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartGamejButton, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanelMenu.setBackground(new java.awt.Color(213, 204, 206));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menú", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanelMenu.setPreferredSize(new java.awt.Dimension(180, 408));

        InstructionsjButton.setBackground(new java.awt.Color(164, 225, 3));
        InstructionsjButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        InstructionsjButton.setText("Instrucciones");
        InstructionsjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 168, 2), 2, true));
        InstructionsjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InstructionsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructionsjButtonActionPerformed(evt);
            }
        });

        SavejButton.setBackground(new java.awt.Color(164, 225, 3));
        SavejButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SavejButton.setText("Guardar");
        SavejButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 168, 2), 2, true));
        SavejButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        LoadGamejButton.setBackground(new java.awt.Color(164, 225, 3));
        LoadGamejButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LoadGamejButton.setText("Cargar Partida");
        LoadGamejButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 168, 2), 2, true));
        LoadGamejButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoadGamejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadGamejButtonActionPerformed(evt);
            }
        });

        ExitjButton.setBackground(new java.awt.Color(249, 173, 107));
        ExitjButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ExitjButton.setText("Salir");
        ExitjButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(247, 139, 45), 2, true));
        ExitjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitjButtonActionPerformed(evt);
            }
        });

        NewGamejButton.setBackground(new java.awt.Color(164, 225, 3));
        NewGamejButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NewGamejButton.setText("Nueva Partida");
        NewGamejButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 168, 2), 2, true));
        NewGamejButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewGamejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGamejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewGamejButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LoadGamejButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(InstructionsjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SavejButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(NewGamejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoadGamejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InstructionsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SavejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanelNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInstruction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelNewGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addComponent(jPanelInstruction, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewGamejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGamejButtonActionPerformed
         
        //Estados de los paneles y botones
        jPanelInstruction.setVisible(false);
        jPanelNewGame.setVisible(true);
        CustomValuesButton.setSelected(false);
        DefaultValuesButton.setSelected(true);
        cityCounter=0;
        
        //Vaciar los campos de inputs
        AntsNumInput.setText("");
        βValueInput.setText("");
        αValueInput.setText("");
        ρValueInput.setText("");
        
    }//GEN-LAST:event_NewGamejButtonActionPerformed

    private void ExitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitjButtonActionPerformed
       
        if (JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas salir? ") == 0){
        
            System.exit(0);
        }
        
    }//GEN-LAST:event_ExitjButtonActionPerformed

    private void AddCityjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCityjButtonActionPerformed
                
        //volver a inicializar los botones y mostrar la pantalla de nuevo juego
        NewCityjPanel.setVisible(true);
        CityNameInput.setEnabled(true);
        CityDistanceInput.setEnabled(false);
        IterationsInput.setEnabled(false);
                
        //Vaciar los campos de inputs
        CityNameInput.setText("");
        CityDistanceInput.setText("");
        IterationsInput.setText("");
        
        
    }//GEN-LAST:event_AddCityjButtonActionPerformed

    private void InstructionsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructionsjButtonActionPerformed
        
        jPanelNewGame.setVisible(false);
        jPanelInstruction.setVisible(true);
        
        
    }//GEN-LAST:event_InstructionsjButtonActionPerformed

    private void AntsNumInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntsNumInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AntsNumInputActionPerformed

    private void LoadGamejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadGamejButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadGamejButtonActionPerformed

    private void AntsNumValidationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntsNumValidationButtonActionPerformed
        
        if (!CityDistanceInput.getText().equals("")) {
                        
            JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas esta cantidad de hormigas? ");
                        
        }
        else {
            
            JOptionPane.showMessageDialog(null, "Campo vacío. Introduzca un valor antes de continuar");
            
        } 
        
    }//GEN-LAST:event_AntsNumValidationButtonActionPerformed

    private void ConfirmNewCityjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmNewCityjButtonActionPerformed

        if (IterationsInput.equals("")) {

            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos antes de continuar");
        }
        else{
            
            cityCounter++;
        }

    }//GEN-LAST:event_ConfirmNewCityjButtonActionPerformed

    private void CustomValuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomValuesButtonActionPerformed

        βValueInput.setEnabled(true);
        αValueInput.setEnabled(true);
        ρValueInput.setEnabled(true);
        DefaultValuesButton.setSelected(false);

    }//GEN-LAST:event_CustomValuesButtonActionPerformed

    private void DefaultValuesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultValuesButtonActionPerformed

        CustomValuesButton.setSelected(false);
        βValueInput.setEnabled(false);
        αValueInput.setEnabled(false);
        ρValueInput.setEnabled(false);

    }//GEN-LAST:event_DefaultValuesButtonActionPerformed

    private void CityDistanceValidationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityDistanceValidationButtonActionPerformed

        if (!CityDistanceInput.getText().equals("")) {

            if (JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas confirmar esta distancia? ") == 0) {

                CityDistanceInput.setEnabled(false);
                IterationsInput.setEnabled(true);
            }
        }
        else {

            JOptionPane.showMessageDialog(null, "Campo vacío. Introduzca un valor antes de continuar");
            IterationsInput.setEnabled(false);
        }

    }//GEN-LAST:event_CityDistanceValidationButtonActionPerformed

    private void CityDistanceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityDistanceInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityDistanceInputActionPerformed

    private void CityNameValidationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityNameValidationButtonActionPerformed

        if (!CityNameInput.getText().equals("")) {

            if (JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas confirmar ese nombre para tu ciudad? ") == 0) {

                CityNameInput.setEnabled(false);
                CityDistanceInput.setEnabled(true);
            }
        }
        else {

            JOptionPane.showMessageDialog(null, "Campo vacío. Introduzca un valor antes de continuar");
            CityDistanceInput.setEnabled(false);
        }
    }//GEN-LAST:event_CityNameValidationButtonActionPerformed

    private void CityNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityNameInputActionPerformed

    }//GEN-LAST:event_CityNameInputActionPerformed

    private void IterationsValidationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IterationsValidationButtonActionPerformed
        
        CustomValuesButton.setEnabled(true);
        DefaultValuesButton.setEnabled(true);
    }//GEN-LAST:event_IterationsValidationButtonActionPerformed

    private void StartGamejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGamejButtonActionPerformed
        
        if (cityCounter<4) {
        
            JOptionPane.showMessageDialog(null, "No puedes empezar tu partida con menos de 4 ciudades");
        }
        else {
            
            if (!AntsNumInput.getText().equals("") && (CustomValuesButton.isSelected() || DefaultValuesButton.isSelected())) {

                if (βValueInput.getText().equals("") || αValueInput.getText().equals("") || ρValueInput.getText().equals("")) {

                    JOptionPane.showMessageDialog(null, "Debes llenar todos los campos antes de continuar");
                }
                else {
                    
                    JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas empezar tu partida con " + cityCounter + " ciudades? ");

                }
            }
            else {

                JOptionPane.showMessageDialog(null, "Debes llenar todos los campos antes de continuar");
            }
                    
        }
    }//GEN-LAST:event_StartGamejButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCityjButton;
    private javax.swing.JTextField AntsNumInput;
    private javax.swing.JButton AntsNumValidationButton;
    private javax.swing.JLabel AntsNumjLabel;
    private javax.swing.JTextField CityDistanceInput;
    private javax.swing.JButton CityDistanceValidationButton;
    private javax.swing.JLabel CityDistancejLabel;
    private javax.swing.JTextField CityNameInput;
    private javax.swing.JButton CityNameValidationButton;
    private javax.swing.JLabel CityNamejLabel1;
    private javax.swing.JButton ConfirmNewCityjButton;
    private javax.swing.JRadioButton CustomValuesButton;
    private javax.swing.JRadioButton DefaultValuesButton;
    private javax.swing.JButton DeleteCityjButton;
    private javax.swing.JButton ExitjButton;
    private javax.swing.JButton InstructionsjButton;
    private javax.swing.JTextField IterationsInput;
    private javax.swing.JButton IterationsValidationButton;
    private javax.swing.JLabel IterationsjLabel;
    private javax.swing.JButton LoadGamejButton;
    private javax.swing.JPanel NewCityjPanel;
    private javax.swing.JButton NewGamejButton;
    private javax.swing.JButton SavejButton;
    private javax.swing.JButton StartGamejButton;
    private javax.swing.JLabel VariablesValuesjLabel1;
    private javax.swing.JPanel jPanelInstruction;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelNewGame;
    private javax.swing.JTextField αValueInput;
    private javax.swing.JLabel αVariableValuejLabel;
    private javax.swing.JTextField βValueInput;
    private javax.swing.JLabel βVariableValuejLabel;
    private javax.swing.JTextField ρValueInput;
    private javax.swing.JLabel ρVariableValuejLabel;
    // End of variables declaration//GEN-END:variables
}
